; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "UB CampusConnect"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "University of Bohol"
#define MyAppURL "https://www.universityofbohol.edu.ph"
#define MyAppExeName "ub_campus_connect.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D3E5F6B7-C8A9-4B5C-BD1E-A2F3B4C5D6E7}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=d:\COLLEGE\4TH YEAR\2ND SEM\THESIS\CampusConnect\installers
OutputBaseFilename=UB_CampusConnect_Setup
SetupIconFile=d:\COLLEGE\4TH YEAR\2ND SEM\THESIS\CampusConnect\campus_connect\windows\runner\resources\app_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "d:\COLLEGE\4TH YEAR\2ND SEM\THESIS\CampusConnect\campus_connect\build\windows\x64\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "d:\COLLEGE\4TH YEAR\2ND SEM\THESIS\CampusConnect\campus_connect\build\windows\x64\runner\Release\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "d:\COLLEGE\4TH YEAR\2ND SEM\THESIS\CampusConnect\campus_connect\build\windows\x64\runner\Release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
; Add any other dlls if present (e.g. plugins)
Source: "d:\COLLEGE\4TH YEAR\2ND SEM\THESIS\CampusConnect\campus_connect\build\windows\x64\runner\Release\*.dll"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall
