; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyProgName "UB Campus Connect"
#define MyProgVersion "1.0.0"
#define MyProgPublisher "University of Bohol"
#define MyProgExeName "ub_campus_connect.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5E9A9B6B-0B8A-4B6B-9B6B-5E9A9B6B0B8A}
AppName={#MyProgName}
AppVersion={#MyProgVersion}
;AppVerName={#MyProgName} {#MyProgVersion}
AppPublisher={#MyProgPublisher}
DefaultDirName={autopf}\{#MyProgName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=..\installer
OutputBaseFilename=UB_Campus_Connect_Setup
SetupIconFile=runner\resources\app_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\build\windows\x64\runner\Release\{#MyProgExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\windows\x64\runner\Release\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\windows\x64\runner\Release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
; Add more files/plugins if necessary
; Source: "..\build\windows\x64\runner\Release\*.dll"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyProgName}"; Filename: "{app}\{#MyProgExeName}"
Name: "{autodesktop}\{#MyProgName}"; Filename: "{app}\{#MyProgExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyProgExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyProgName, '&', '&&')}}"; Flags: nowait postinstall skipifdoesntexist
