// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsl2Qw7JnnTB-2ZxTAOS6qga7VK4lnGvc',
    appId: '1:201204650015:web:7c96a7bd470abc594d052a',
    messagingSenderId: '201204650015',
    projectId: 'campusconnect-ub',
    authDomain: 'campusconnect-ub.firebaseapp.com',
    storageBucket: 'campusconnect-ub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiyIlV8RfKbVdRY09i15PslY0Jf1mF-zU',
    appId: '1:201204650015:android:99976b1b9c268a6a4d052a',
    messagingSenderId: '201204650015',
    projectId: 'campusconnect-ub',
    storageBucket: 'campusconnect-ub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVJhZWNRnSyybGuAyTYG44WX9VYof4orI',
    appId: '1:201204650015:ios:eb962a1f286f35e04d052a',
    messagingSenderId: '201204650015',
    projectId: 'campusconnect-ub',
    storageBucket: 'campusconnect-ub.firebasestorage.app',
    iosBundleId: 'com.example.ccAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsl2Qw7JnnTB-2ZxTAOS6qga7VK4lnGvc',
    appId: '1:201204650015:web:587030a9df90d7474d052a',
    messagingSenderId: '201204650015',
    projectId: 'campusconnect-ub',
    authDomain: 'campusconnect-ub.firebaseapp.com',
    storageBucket: 'campusconnect-ub.firebasestorage.app',
  );

}